[package]
name = "asm465"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.24", features = ["default_fonts", "glow"] }
bus = { path = "../cross465/bus" }
core6502 = { path = "../cross465/core6502" }
clap = { version = "4", features = ["derive"], optional = true }
crossbeam-channel = { version = "0.5", optional = true }
rfd = { version = "0.14", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21"

[features]
default = ["native-service", "native-file-dialog"]
native-service = ["crossbeam-channel", "clap"]
native-file-dialog = ["rfd"]
web-service = []

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["windef", "winuser"] }
