[workspace]
members = ["bus","core6502", "cross465-runner","runtime_sdk"]
resolver = "2"

[workspace.lints.rust]
unsafe_code = "deny"
unused_must_use = "deny"
missing_debug_implementations = "allow"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "allow", priority = -1 }
